version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: app
    restart: always
    env_file: 
      - ./env_files/.env
    volumes:
      - ./app:/app
      - ./web/static:/web/static
      - ./web/media:/web/media
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internal-network
    depends_on:
      - psql
  
  psql:
    image: postgres:15.7-bullseye
    container_name: psql
    restart: always
    env_file: 
      - ./env_files/.env
    ports:
      - 5432:5432
    networks:
      - internal-network
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: nginx
    env_file:
      - ./env_files/.env.nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./web/static:/web/static
      - ./web/media:/web/media
      - ./nginx/templates:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    networks:
      - internal-network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >- 
            certonly --reinstall --webroot --webroot-path=/var/www/certbot
            --email fernando.quimic@gmail.com --agree-tos --no-eff-email
            -d whys.brainstormtech.com.br
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
