version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine3.19
    env_file:
      - ./env_files/.env.nginx
    ports:
      - 80:80
    volumes:
      - ./web/static:/web/static
      - ./web/media:/web/media
      - ./nginx/templates-initiate:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    networks:
      - internal-network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >- 
            certonly --reinstall --webroot --webroot-path=/var/www/certbot
            --email fernando.quimic@gmial.com --agree-tos --no-eff-email
            -d whys.brainstormtech.com.br
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge