# Generated by Django 5.0.1 on 2024-02-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id_loc', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('coordinate', models.CharField(
                    blank=True, max_length=100, null=True, unique=True
                )),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sen', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=20, unique=True)),
                ('id_localization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.localization')),
            ],
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id_data_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('date_hour', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sensor')),
            ],
        ),
    ]
