# Generated by Django 5.0.1 on 2024-02-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_sensor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.localization'),
        ),
    ]
