# Generated by Django 5.0.1 on 2024-02-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_sensor_id_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='coordinate',
            field=models.CharField(blank=True, default='Sem Coordenadas...', max_length=100, null=True, unique=True),
        ),
    ]
